# Generated by Django 3.2 on 2021-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность курса')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование события')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Период события',
                'verbose_name_plural': 'Временные интервалы событий',
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_num', models.CharField(max_length=255, verbose_name='Номер группы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала группы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания группы')),
                ('group_status', models.CharField(max_length=10, verbose_name='Статус группы')),
                ('person_cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость обучения 1 человека')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.courses')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=255, verbose_name='Номер/наименование аудитории')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О преподавателе')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.events', verbose_name='Событие')),
                ('event_time_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.eventtime', verbose_name='Время события')),
                ('group_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.groups', verbose_name='Группа')),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.rooms', verbose_name='Аудитория')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Событие в расписании',
                'verbose_name_plural': 'Раписание',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teachers'),
        ),
    ]
